/**
 * Theme definitions for Notepad++ Web.
 *
 * The themes are derived directly from the GlobalStyles sections of the XML
 * theme files shipped with the Notepad++ desktop application
 * (PowerEditor/installer/themes/*.xml). CSS custom properties are computed
 * from each theme's editor colours so that the full application chrome
 * (menu bar, toolbars, dialogs, tabs) matches the chosen editor palette.
 *
 * One additional web-native theme ("Modern Web") is included that makes the
 * app look like a contemporary browser application rather than a Windows
 * desktop program.
 *
 * Themes are applied by writing CSS custom properties onto <html> via
 * document.documentElement.style.setProperty().
 */

export const THEMES = [
  {
    id: 'classic',
    name: 'Default (Notepad++)',
    description: 'The classic Notepad++ look — faithful to the Windows desktop application.',
    variables: {
      '--chrome-bg': '#f0f0f0',
      '--chrome-bg-raised': '#f5f5f5',
      '--chrome-bg-title': '#dcdcdc',
      '--chrome-border': '#a0a0a0',
      '--chrome-border-light': '#d0d0d0',
      '--chrome-text': '#000000',
      '--chrome-text-muted': '#333333',
      '--chrome-text-subtle': '#555555',
      '--chrome-hover': '#d8d8d8',
      '--chrome-separator': '#c0c0c0',
      '--accent': '#0078d4',
      '--accent-text': '#ffffff',
      '--tab-bar-bg': '#bdbdbd',
      '--tab-inactive-bg': '#d4d0c8',
      '--tab-inactive-text': '#333333',
      '--tab-active-bg': '#ffffff',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#e8e8e0',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#ffffff',
      '--editor-fg': '#000000',
      '--editor-gutter-bg': '#f0f0f0',
      '--editor-gutter-fg': '#888888',
      '--editor-gutter-border': '#d0d0d0',
      '--btn-bg': '#e8e8e8',
      '--btn-hover-bg': '#d0d0d0',
      '--btn-border': '#a0a0a0',
      '--btn-text': '#000000',
      '--input-bg': '#ffffff',
      '--input-border': '#a0a0a0',
      '--dialog-bg': '#f5f5f5',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.3)',
      '--dialog-radius': '0px',
      '--font-ui': "\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif",
      '--font-editor': "\'Courier New\', Courier, monospace",
      '--ui-radius': '2px',
    },
  },
  {
    id: 'bespin',
    name: 'Bespin',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#39302B',
      '--chrome-bg-raised': '#403732',
      '--chrome-bg-title': '#483F3A',
      '--chrome-border': '#5C534E',
      '--chrome-border-light': '#504742',
      '--chrome-text': '#BDAE9D',
      '--chrome-text-muted': '#988A7C',
      '--chrome-text-subtle': '#7A6E62',
      '--chrome-hover': '#433A35',
      '--chrome-separator': '#544B46',
      '--accent': '#83675A',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#362D28',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#504742',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#433A35',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#2A211C',
      '--editor-fg': '#BDAE9D',
      '--editor-gutter-bg': '#4C4A41',
      '--editor-gutter-fg': '#E5C138',
      '--editor-gutter-border': '#403B34',
      '--btn-bg': '#403732',
      '--btn-hover-bg': '#4A413C',
      '--btn-border': '#5C534E',
      '--btn-text': '#BDAE9D',
      '--input-bg': '#342B26',
      '--input-border': '#544B46',
      '--dialog-bg': '#382F2A',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'DejaVu Sans Mono\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'black-board',
    name: 'Black board',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#1B1F30',
      '--chrome-bg-raised': '#222637',
      '--chrome-bg-title': '#2A2E3F',
      '--chrome-border': '#3E4253',
      '--chrome-border-light': '#323647',
      '--chrome-text': '#F8F8F8',
      '--chrome-text-muted': '#BDBEC2',
      '--chrome-text-subtle': '#8D8F97',
      '--chrome-hover': '#25293A',
      '--chrome-separator': '#363A4B',
      '--accent': '#253B76',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#181C2D',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#323647',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#25293A',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#0C1021',
      '--editor-fg': '#F8F8F8',
      '--editor-gutter-bg': '#2E3436',
      '--editor-gutter-fg': '#EEEEEC',
      '--editor-gutter-border': '#22272E',
      '--btn-bg': '#222637',
      '--btn-hover-bg': '#2C3041',
      '--btn-border': '#3E4253',
      '--btn-text': '#F8F8F8',
      '--input-bg': '#161A2B',
      '--input-border': '#363A4B',
      '--dialog-bg': '#1A1E2F',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'DejaVu Sans Mono\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'choco',
    name: 'Choco',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#291E1A',
      '--chrome-bg-raised': '#302521',
      '--chrome-bg-title': '#382D29',
      '--chrome-border': '#4C413D',
      '--chrome-border-light': '#403531',
      '--chrome-text': '#C3BE98',
      '--chrome-text-muted': '#989274',
      '--chrome-text-subtle': '#766F58',
      '--chrome-hover': '#332824',
      '--chrome-separator': '#443935',
      '--accent': '#372017',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#261B17',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#403531',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#332824',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#1A0F0B',
      '--editor-fg': '#C3BE98',
      '--editor-gutter-bg': '#2E3436',
      '--editor-gutter-fg': '#EEEEEC',
      '--editor-gutter-border': '#272726',
      '--btn-bg': '#302521',
      '--btn-hover-bg': '#3A2F2B',
      '--btn-border': '#4C413D',
      '--btn-text': '#C3BE98',
      '--input-bg': '#241915',
      '--input-border': '#443935',
      '--dialog-bg': '#281D19',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'DejaVu Sans Mono\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'danslerush-dark',
    name: 'DansLeRuSH-Dark',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#3D3D3D',
      '--chrome-bg-raised': '#444444',
      '--chrome-bg-title': '#4C4C4C',
      '--chrome-border': '#606060',
      '--chrome-border-light': '#545454',
      '--chrome-text': '#C7C7C7',
      '--chrome-text-muted': '#A0A0A0',
      '--chrome-text-subtle': '#828282',
      '--chrome-hover': '#474747',
      '--chrome-separator': '#585858',
      '--accent': '#4D4D4D',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#3A3A3A',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#545454',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#474747',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#2E2E2E',
      '--editor-fg': '#C7C7C7',
      '--editor-gutter-bg': '#363636',
      '--editor-gutter-fg': '#8F8F8F',
      '--editor-gutter-border': '#333333',
      '--btn-bg': '#444444',
      '--btn-hover-bg': '#4E4E4E',
      '--btn-border': '#606060',
      '--btn-text': '#C7C7C7',
      '--input-bg': '#383838',
      '--input-border': '#585858',
      '--dialog-bg': '#3C3C3C',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Source Code Pro\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'darkmodedefault',
    name: 'DarkModeDefault',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#4E4E4E',
      '--chrome-bg-raised': '#555555',
      '--chrome-bg-title': '#5D5D5D',
      '--chrome-border': '#717171',
      '--chrome-border-light': '#656565',
      '--chrome-text': '#DCDCCC',
      '--chrome-text-muted': '#B4B4A8',
      '--chrome-text-subtle': '#95958C',
      '--chrome-hover': '#585858',
      '--chrome-separator': '#696969',
      '--accent': '#585858',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#4B4B4B',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#656565',
      '--tab-active-text': '#101010',
      '--tab-hover-bg': '#585858',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#3F3F3F',
      '--editor-fg': '#DCDCCC',
      '--editor-gutter-bg': '#0C0C0C',
      '--editor-gutter-fg': '#8A8A8A',
      '--editor-gutter-border': '#1D1D1D',
      '--btn-bg': '#555555',
      '--btn-hover-bg': '#5F5F5F',
      '--btn-border': '#717171',
      '--btn-text': '#DCDCCC',
      '--input-bg': '#494949',
      '--input-border': '#696969',
      '--dialog-bg': '#4D4D4D',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Consolas\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'deep-black',
    name: 'Deep Black',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#0F0F0F',
      '--chrome-bg-raised': '#161616',
      '--chrome-bg-title': '#1E1E1E',
      '--chrome-border': '#323232',
      '--chrome-border-light': '#262626',
      '--chrome-text': '#FFFFFF',
      '--chrome-text-muted': '#BFBFBF',
      '--chrome-text-subtle': '#8C8C8C',
      '--chrome-hover': '#191919',
      '--chrome-separator': '#2A2A2A',
      '--accent': '#6699CC',
      '--accent-text': '#000000',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#0C0C0C',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#262626',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#191919',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#000000',
      '--editor-fg': '#FFFFFF',
      '--editor-gutter-bg': '#333333',
      '--editor-gutter-fg': '#C0C0C0',
      '--editor-gutter-border': '#212121',
      '--btn-bg': '#161616',
      '--btn-hover-bg': '#202020',
      '--btn-border': '#323232',
      '--btn-text': '#FFFFFF',
      '--input-bg': '#0A0A0A',
      '--input-border': '#2A2A2A',
      '--dialog-bg': '#0E0E0E',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Courier New\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'hello-kitty',
    name: 'Hello Kitty',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#F6D6F6',
      '--chrome-bg-raised': '#F8E0F8',
      '--chrome-bg-title': '#EACAEA',
      '--chrome-border': '#C6A6C6',
      '--chrome-border-light': '#E2C3E2',
      '--chrome-text': '#000000',
      '--chrome-text-muted': '#333333',
      '--chrome-text-subtle': '#666666',
      '--chrome-hover': '#E7C8E7',
      '--chrome-separator': '#D9B9D9',
      '--accent': '#FFFFFF',
      '--accent-text': '#000000',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#E9C0E3',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#FFB0FF',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#F4B8F1',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#FFB0FF',
      '--editor-fg': '#000000',
      '--editor-gutter-bg': '#FF80FF',
      '--editor-gutter-fg': '#FFFFFF',
      '--editor-gutter-border': '#FF90FF',
      '--btn-bg': '#F1D1F1',
      '--btn-hover-bg': '#E2C3E2',
      '--btn-border': '#C6A6C6',
      '--btn-text': '#000000',
      '--input-bg': '#FFB0FF',
      '--input-border': '#C6A6C6',
      '--dialog-bg': '#F8E0F8',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.3)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Courier New\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'hotfudgesundae',
    name: 'HotFudgeSundae',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#3A1E10',
      '--chrome-bg-raised': '#412517',
      '--chrome-bg-title': '#492D1F',
      '--chrome-border': '#5D4133',
      '--chrome-border-light': '#513527',
      '--chrome-text': '#B7975D',
      '--chrome-text-muted': '#947546',
      '--chrome-text-subtle': '#785933',
      '--chrome-hover': '#44281A',
      '--chrome-separator': '#55392B',
      '--accent': '#585858',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#D5BC93',
      '--tab-inactive-bg': '#371B0D',
      '--tab-inactive-text': '#43250B',
      '--tab-active-bg': '#513527',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#44281A',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#2B0F01',
      '--editor-fg': '#B7975D',
      '--editor-gutter-bg': '#43250B',
      '--editor-gutter-fg': '#8B642B',
      '--editor-gutter-border': '#3A1D07',
      '--btn-bg': '#412517',
      '--btn-hover-bg': '#4B2F21',
      '--btn-border': '#5D4133',
      '--btn-text': '#B7975D',
      '--input-bg': '#35190B',
      '--input-border': '#55392B',
      '--dialog-bg': '#391D0F',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Consolas\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'mono-industrial',
    name: 'Mono Industrial',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#313B37',
      '--chrome-bg-raised': '#38423E',
      '--chrome-bg-title': '#404A46',
      '--chrome-border': '#545E5A',
      '--chrome-border-light': '#48524E',
      '--chrome-text': '#FFFFFF',
      '--chrome-text-muted': '#C7CAC9',
      '--chrome-text-subtle': '#9BA09E',
      '--chrome-hover': '#3B4541',
      '--chrome-separator': '#4C5652',
      '--accent': '#919994',
      '--accent-text': '#000000',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#2E3834',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#48524E',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#3B4541',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#222C28',
      '--editor-fg': '#FFFFFF',
      '--editor-gutter-bg': '#2E3436',
      '--editor-gutter-fg': '#EEEEEC',
      '--editor-gutter-border': '#293131',
      '--btn-bg': '#38423E',
      '--btn-hover-bg': '#424C48',
      '--btn-border': '#545E5A',
      '--btn-text': '#FFFFFF',
      '--input-bg': '#2C3632',
      '--input-border': '#4C5652',
      '--dialog-bg': '#303A36',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'DejaVu Sans Mono\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#363731',
      '--chrome-bg-raised': '#3D3E38',
      '--chrome-bg-title': '#454640',
      '--chrome-border': '#595A54',
      '--chrome-border-light': '#4D4E48',
      '--chrome-text': '#F8F8F2',
      '--chrome-text-muted': '#C3C4BE',
      '--chrome-text-subtle': '#999A94',
      '--chrome-hover': '#40413B',
      '--chrome-separator': '#51524C',
      '--accent': '#49483E',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#33342E',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#4D4E48',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#40413B',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#272822',
      '--editor-fg': '#F8F8F2',
      '--editor-gutter-bg': '#2E3436',
      '--editor-gutter-fg': '#EEEEEC',
      '--editor-gutter-border': '#2B2F2F',
      '--btn-bg': '#3D3E38',
      '--btn-hover-bg': '#474842',
      '--btn-border': '#595A54',
      '--btn-text': '#F8F8F2',
      '--input-bg': '#31322C',
      '--input-border': '#51524C',
      '--dialog-bg': '#353630',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'DejaVu Sans Mono\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'mossylawn',
    name: 'MossyLawn',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#B3BAA8',
      '--chrome-bg-raised': '#C5CBBD',
      '--chrome-bg-title': '#A7AE9C',
      '--chrome-border': '#838A78',
      '--chrome-border-light': '#A0A695',
      '--chrome-text': '#000000',
      '--chrome-text-muted': '#333333',
      '--chrome-text-subtle': '#666666',
      '--chrome-hover': '#A4AB9A',
      '--chrome-separator': '#969D8B',
      '--accent': '#8B6733',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#BBCF60',
      '--tab-inactive-bg': '#969C82',
      '--tab-inactive-text': '#162504',
      '--tab-active-bg': '#58693D',
      '--tab-active-text': '#012001',
      '--tab-hover-bg': '#77825F',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#58693D',
      '--editor-fg': '#F2C476',
      '--editor-gutter-bg': '#7E8A28',
      '--editor-gutter-fg': '#603D13',
      '--editor-gutter-border': '#707E2F',
      '--btn-bg': '#AEB5A3',
      '--btn-hover-bg': '#A0A695',
      '--btn-border': '#838A78',
      '--btn-text': '#000000',
      '--input-bg': '#58693D',
      '--input-border': '#838A78',
      '--dialog-bg': '#C5CBBD',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.3)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Consolas\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'navajo',
    name: 'Navajo',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#DACEC3',
      '--chrome-bg-raised': '#E3DAD1',
      '--chrome-bg-title': '#CEC2B7',
      '--chrome-border': '#AA9E93',
      '--chrome-border-light': '#C7BBB0',
      '--chrome-text': '#000000',
      '--chrome-text-muted': '#333333',
      '--chrome-text-subtle': '#666666',
      '--chrome-hover': '#CCC0B4',
      '--chrome-separator': '#BDB1A6',
      '--accent': '#BCBCBC',
      '--accent-text': '#000000',
      '--tab-bar-bg': '#BA9C80',
      '--tab-inactive-bg': '#C7B6A4',
      '--tab-inactive-text': '#181880',
      '--tab-active-bg': '#BA9C80',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#C0A992',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#BA9C80',
      '--editor-fg': '#000000',
      '--editor-gutter-bg': '#808080',
      '--editor-gutter-fg': '#000000',
      '--editor-gutter-border': '#948980',
      '--btn-bg': '#D5C9BE',
      '--btn-hover-bg': '#C7BBB0',
      '--btn-border': '#AA9E93',
      '--btn-text': '#000000',
      '--input-bg': '#BA9C80',
      '--input-border': '#AA9E93',
      '--dialog-bg': '#E3DAD1',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.3)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Consolas\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#384043',
      '--chrome-bg-raised': '#3F474A',
      '--chrome-bg-title': '#474F52',
      '--chrome-border': '#5B6366',
      '--chrome-border-light': '#4F575A',
      '--chrome-text': '#E0E2E4',
      '--chrome-text-muted': '#B2B5B8',
      '--chrome-text-subtle': '#8D9294',
      '--chrome-hover': '#424A4D',
      '--chrome-separator': '#535B5E',
      '--accent': '#404E51',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#353D40',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#4F575A',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#424A4D',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#293134',
      '--editor-fg': '#E0E2E4',
      '--editor-gutter-bg': '#3F4B4E',
      '--editor-gutter-fg': '#81969A',
      '--editor-gutter-border': '#374144',
      '--btn-bg': '#3F474A',
      '--btn-hover-bg': '#495154',
      '--btn-border': '#5B6366',
      '--btn-text': '#E0E2E4',
      '--input-bg': '#333B3E',
      '--input-border': '#535B5E',
      '--dialog-bg': '#373F42',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Courier New\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'plastic-code-wrap',
    name: 'Plastic Code Wrap',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#1A252C',
      '--chrome-bg-raised': '#212C33',
      '--chrome-bg-title': '#29343B',
      '--chrome-border': '#3D484F',
      '--chrome-border-light': '#313C43',
      '--chrome-text': '#F8F8F8',
      '--chrome-text-muted': '#BCBFC1',
      '--chrome-text-subtle': '#8D9295',
      '--chrome-hover': '#242F36',
      '--chrome-separator': '#354047',
      '--accent': '#162E3D',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#172229',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#313C43',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#242F36',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#0B161D',
      '--editor-fg': '#F8F8F8',
      '--editor-gutter-bg': '#2E3436',
      '--editor-gutter-fg': '#EEEEEC',
      '--editor-gutter-border': '#21292D',
      '--btn-bg': '#212C33',
      '--btn-hover-bg': '#2B363D',
      '--btn-border': '#3D484F',
      '--btn-text': '#F8F8F8',
      '--input-bg': '#152027',
      '--input-border': '#354047',
      '--dialog-bg': '#19242B',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'DejaVu Sans Mono\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'ruby-blue',
    name: 'Ruby Blue',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#203344',
      '--chrome-bg-raised': '#273A4B',
      '--chrome-bg-title': '#2F4253',
      '--chrome-border': '#435667',
      '--chrome-border-light': '#374A5B',
      '--chrome-text': '#FFFFFF',
      '--chrome-text-muted': '#C3C8CC',
      '--chrome-text-subtle': '#939CA4',
      '--chrome-hover': '#2A3D4E',
      '--chrome-separator': '#3B4E5F',
      '--accent': '#0000FF',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#1D3041',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#374A5B',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#2A3D4E',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#112435',
      '--editor-fg': '#FFFFFF',
      '--editor-gutter-bg': '#1F4661',
      '--editor-gutter-fg': '#FFFFFF',
      '--editor-gutter-border': '#1A3A51',
      '--btn-bg': '#273A4B',
      '--btn-hover-bg': '#314455',
      '--btn-border': '#435667',
      '--btn-text': '#FFFFFF',
      '--input-bg': '#1B2E3F',
      '--input-border': '#3B4E5F',
      '--dialog-bg': '#1F3243',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'DejaVu Sans Mono\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'solarized-light',
    name: 'Solarized-light',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#F5F2EA',
      '--chrome-bg-raised': '#F7F5EF',
      '--chrome-bg-title': '#E9E6DE',
      '--chrome-border': '#C5C2BA',
      '--chrome-border-light': '#E2DFD7',
      '--chrome-text': '#000000',
      '--chrome-text-muted': '#333333',
      '--chrome-text-subtle': '#666666',
      '--chrome-hover': '#E6E4DC',
      '--chrome-separator': '#D8D5CE',
      '--accent': '#073642',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#93A1A1',
      '--tab-inactive-bg': '#E8E3D5',
      '--tab-inactive-text': '#073642',
      '--tab-active-bg': '#FDF6E3',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#F2ECDC',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#FDF6E3',
      '--editor-fg': '#657B83',
      '--editor-gutter-bg': '#EEE8D5',
      '--editor-gutter-fg': '#93A1A1',
      '--editor-gutter-border': '#F3ECD9',
      '--btn-bg': '#F0EDE6',
      '--btn-hover-bg': '#E2DFD7',
      '--btn-border': '#C5C2BA',
      '--btn-text': '#000000',
      '--input-bg': '#FDF6E3',
      '--input-border': '#C5C2BA',
      '--dialog-bg': '#F7F5EF',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.3)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Consolas\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'solarized',
    name: 'Solarized',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#0F3A45',
      '--chrome-bg-raised': '#16414C',
      '--chrome-bg-title': '#1E4954',
      '--chrome-border': '#325D68',
      '--chrome-border-light': '#26515C',
      '--chrome-text': '#839496',
      '--chrome-text-muted': '#62797E',
      '--chrome-text-subtle': '#48646A',
      '--chrome-hover': '#19444F',
      '--chrome-separator': '#2A5560',
      '--accent': '#EEE8D5',
      '--accent-text': '#000000',
      '--tab-bar-bg': '#586E75',
      '--tab-inactive-bg': '#0C3742',
      '--tab-inactive-text': '#EEE8D5',
      '--tab-active-bg': '#26515C',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#19444F',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#002B36',
      '--editor-fg': '#839496',
      '--editor-gutter-bg': '#073642',
      '--editor-gutter-fg': '#586E75',
      '--editor-gutter-border': '#04323D',
      '--btn-bg': '#16414C',
      '--btn-hover-bg': '#204B56',
      '--btn-border': '#325D68',
      '--btn-text': '#839496',
      '--input-bg': '#0A3540',
      '--input-border': '#2A5560',
      '--dialog-bg': '#0E3944',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Consolas\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'twilight',
    name: 'Twilight',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#232323',
      '--chrome-bg-raised': '#2A2A2A',
      '--chrome-bg-title': '#323232',
      '--chrome-border': '#464646',
      '--chrome-border-light': '#3A3A3A',
      '--chrome-text': '#F8F8F8',
      '--chrome-text-muted': '#BFBFBF',
      '--chrome-text-subtle': '#919191',
      '--chrome-hover': '#2D2D2D',
      '--chrome-separator': '#3E3E3E',
      '--accent': '#3E3E3E',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#202020',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#3A3A3A',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#2D2D2D',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#141414',
      '--editor-fg': '#F8F8F8',
      '--editor-gutter-bg': '#2E3436',
      '--editor-gutter-fg': '#EEEEEC',
      '--editor-gutter-border': '#24282A',
      '--btn-bg': '#2A2A2A',
      '--btn-hover-bg': '#343434',
      '--btn-border': '#464646',
      '--btn-text': '#F8F8F8',
      '--input-bg': '#1E1E1E',
      '--input-border': '#3E3E3E',
      '--dialog-bg': '#222222',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Consolas\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'vibrant-ink',
    name: 'Vibrant Ink',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#0F0F0F',
      '--chrome-bg-raised': '#161616',
      '--chrome-bg-title': '#1E1E1E',
      '--chrome-border': '#323232',
      '--chrome-border-light': '#262626',
      '--chrome-text': '#FFFFFF',
      '--chrome-text-muted': '#BFBFBF',
      '--chrome-text-subtle': '#8C8C8C',
      '--chrome-hover': '#191919',
      '--chrome-separator': '#2A2A2A',
      '--accent': '#6699CC',
      '--accent-text': '#000000',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#0C0C0C',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#262626',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#191919',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#000000',
      '--editor-fg': '#FFFFFF',
      '--editor-gutter-bg': '#333333',
      '--editor-gutter-fg': '#E4E4E4',
      '--editor-gutter-border': '#212121',
      '--btn-bg': '#161616',
      '--btn-hover-bg': '#202020',
      '--btn-border': '#323232',
      '--btn-text': '#FFFFFF',
      '--input-bg': '#0A0A0A',
      '--input-border': '#2A2A2A',
      '--dialog-bg': '#0E0E0E',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Monaco\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'zenburn',
    name: 'Zenburn',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#4E4E4E',
      '--chrome-bg-raised': '#555555',
      '--chrome-bg-title': '#5D5D5D',
      '--chrome-border': '#717171',
      '--chrome-border-light': '#656565',
      '--chrome-text': '#DCDCCC',
      '--chrome-text-muted': '#B4B4A8',
      '--chrome-text-subtle': '#95958C',
      '--chrome-hover': '#585858',
      '--chrome-separator': '#696969',
      '--accent': '#585858',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#C0C0C0',
      '--tab-inactive-bg': '#4B4B4B',
      '--tab-inactive-text': '#808080',
      '--tab-active-bg': '#656565',
      '--tab-active-text': '#101010',
      '--tab-hover-bg': '#585858',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#3F3F3F',
      '--editor-fg': '#DCDCCC',
      '--editor-gutter-bg': '#0C0C0C',
      '--editor-gutter-fg': '#8A8A8A',
      '--editor-gutter-border': '#1D1D1D',
      '--btn-bg': '#555555',
      '--btn-hover-bg': '#5F5F5F',
      '--btn-border': '#717171',
      '--btn-text': '#DCDCCC',
      '--input-bg': '#494949',
      '--input-border': '#696969',
      '--dialog-bg': '#4D4D4D',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Consolas\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'khaki',
    name: 'khaki',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#E6E6D6',
      '--chrome-bg-raised': '#ECECE0',
      '--chrome-bg-title': '#DADACA',
      '--chrome-border': '#B6B6A6',
      '--chrome-border-light': '#D2D2C2',
      '--chrome-text': '#000000',
      '--chrome-text-muted': '#333333',
      '--chrome-text-subtle': '#666666',
      '--chrome-hover': '#D7D7C7',
      '--chrome-separator': '#C9C9B9',
      '--accent': '#5F5F00',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#D7D7AF',
      '--tab-inactive-bg': '#D5D3BB',
      '--tab-inactive-text': '#5F5F00',
      '--tab-active-bg': '#D7D7AF',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#D6D5B5',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#D7D7AF',
      '--editor-fg': '#5F5F00',
      '--editor-gutter-bg': '#AFAF87',
      '--editor-gutter-fg': '#5F5F00',
      '--editor-gutter-border': '#BDBD95',
      '--btn-bg': '#E1E1D1',
      '--btn-hover-bg': '#D2D2C2',
      '--btn-border': '#B6B6A6',
      '--btn-text': '#000000',
      '--input-bg': '#D7D7AF',
      '--input-border': '#B6B6A6',
      '--dialog-bg': '#ECECE0',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.3)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Consolas\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'vim-dark-blue',
    name: 'vim Dark Blue',
    description: 'Notepad++ built-in theme.',
    variables: {
      '--chrome-bg': '#0F0F4F',
      '--chrome-bg-raised': '#161656',
      '--chrome-bg-title': '#1E1E5E',
      '--chrome-border': '#323272',
      '--chrome-border-light': '#262666',
      '--chrome-text': '#FFFFBF',
      '--chrome-text-muted': '#BFBF9F',
      '--chrome-text-subtle': '#8C8C85',
      '--chrome-hover': '#191959',
      '--chrome-separator': '#2A2A6A',
      '--accent': '#2050D0',
      '--accent-text': '#FFFFFF',
      '--tab-bar-bg': '#CECECE',
      '--tab-inactive-bg': '#0C0C4C',
      '--tab-inactive-text': '#8080C0',
      '--tab-active-bg': '#262666',
      '--tab-active-text': '#000000',
      '--tab-hover-bg': '#191959',
      '--tab-radius': '3px 3px 0 0',
      '--editor-bg': '#000040',
      '--editor-fg': '#FFFFBF',
      '--editor-gutter-bg': '#000040',
      '--editor-gutter-fg': '#FFFFFF',
      '--editor-gutter-border': '#000040',
      '--btn-bg': '#161656',
      '--btn-hover-bg': '#202060',
      '--btn-border': '#323272',
      '--btn-text': '#FFFFBF',
      '--input-bg': '#0A0A4A',
      '--input-border': '#2A2A6A',
      '--dialog-bg': '#0E0E4E',
      '--dialog-shadow': '4px 4px 8px rgba(0, 0, 0, 0.5)',
      '--dialog-radius': '0px',
      '--font-ui': '\'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif',
      '--font-editor': '\'Consolas\', \'Courier New\', Courier, monospace',
      '--ui-radius': '2px',
    },
  },
  {
    id: 'modern',
    name: 'Modern Web',
    description:
      'A clean, contemporary web design — smooth curves, soft depth, and a system font stack.',
    variables: {
      '--chrome-bg': '#ffffff',
      '--chrome-bg-raised': '#f8f9fa',
      '--chrome-bg-title': '#f1f3f5',
      '--chrome-border': '#dee2e6',
      '--chrome-border-light': '#e9ecef',
      '--chrome-text': '#212529',
      '--chrome-text-muted': '#495057',
      '--chrome-text-subtle': '#6c757d',
      '--chrome-hover': '#f1f3f5',
      '--chrome-separator': '#dee2e6',
      '--accent': '#228be6',
      '--accent-text': '#ffffff',
      '--tab-bar-bg': '#f1f3f5',
      '--tab-inactive-bg': '#e9ecef',
      '--tab-inactive-text': '#495057',
      '--tab-active-bg': '#ffffff',
      '--tab-active-text': '#212529',
      '--tab-hover-bg': '#f8f9fa',
      '--tab-radius': '8px 8px 0 0',
      '--editor-bg': '#ffffff',
      '--editor-fg': '#212529',
      '--editor-gutter-bg': '#f8f9fa',
      '--editor-gutter-fg': '#adb5bd',
      '--editor-gutter-border': '#dee2e6',
      '--btn-bg': '#f8f9fa',
      '--btn-hover-bg': '#e9ecef',
      '--btn-border': '#ced4da',
      '--btn-text': '#212529',
      '--input-bg': '#ffffff',
      '--input-border': '#ced4da',
      '--dialog-bg': '#ffffff',
      '--dialog-shadow': '0 20px 60px rgba(0, 0, 0, 0.12), 0 4px 16px rgba(0, 0, 0, 0.08)',
      '--dialog-radius': '12px',
      '--font-ui':
        "\'Inter\', system-ui, -apple-system, BlinkMacSystemFont, \'Segoe UI\', sans-serif",
      '--font-editor':
        "\'JetBrains Mono\', \'Fira Code\', \'Cascadia Code\', \'Courier New\', monospace",
      '--ui-radius': '6px',
    },
  },
]

export const DEFAULT_THEME_ID = 'classic'

/** Apply a theme's CSS variables to the document root. */
export function applyTheme(themeId) {
  const theme = THEMES.find((t) => t.id === themeId) ?? THEMES[0]
  const root = document.documentElement
  for (const [prop, value] of Object.entries(theme.variables)) {
    root.style.setProperty(prop, value)
  }
}
